### ISSUE TITLE
docker pull 不下来镜像，是否是镜像不存在了

### ISSUE THREAD

**Issue by xxllp** [ucloud/uai-sdk#48]
docker pull uhub.service.ucloud.cn/uai_demo/slim_infer:latest
Error response from daemon: pull access denied for uhub.service.ucloud.cn/uai_demo/slim_infer, repository does not exist or may require 'docker login'

**Comment by xxllp** [comment]
我已经登录了还是报错

**Comment by classicsong** [comment]
你是否注册了ucloud的账号，然后docker login 过了

**Comment by xxllp** [comment]
那具体我该怎么操作呢

**Comment by classicsong** [comment]
https://github.com/ucloud/uai-sdk/tree/master/examples/tensorflow/train/slim/train 这里的Readme里面有说明和例子的Dockerfile
