### ISSUE TITLE
Error with --email flag deprecation for `docker login`

### ISSUE THREAD

**Issue by stevefermi** [ucloud/uai-sdk#5]
https://github.com/ucloud/uai-sdk/blob/1b09138e73c7e71512d11dc341e99335a4eee7ea/uaitrain/operation/pack_docker_image/base_pack_op.py#L317

It causes some problems on latest docker version. More details will be attached later.

I think the client should check the docker version first

**Comment by stevefermi** [comment]
By the way, it should be docker_register instead of dcoker_register. :P

**Comment by classicsong** [comment]
The commit has been merged.
Mark this issue as closed.
